### ISSUE TITLE
appointment bugs

### ISSUE THREAD

**Issue by derekjxtan** [AY2324S1-CS2103T-T08-1/tp#170]
Fix this list after finishing the rest of the implementations. add to this list if any further bugs are found.

1. list_a error message missing space before 'dic', missing newline before parameters, missing working example
<img width="519" alt="image" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/59358844/e54a2602-aaaf-46f0-91f4-a7ff7323062d">

2. add_a start time = end time shows: end time cannot be **before** start time

3. add_a error message missing new line before parameters, missing working example

4. Nric with missing too missing numbers shows: NRIC should only contain alphanumeric characters and it should not be blank (NRIC bug, will move this out of here afterwards)

5. Mismatch between error messages for view_a -1 and view_a 10000. (not isolated to appointment, whether to treat this as a bug is tbc, just need to ensure that user guide reflects accordingly)

6. remark_a incorrect success message.
<img width="662" alt="image" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/59358844/879c5266-dfbb-4df7-866a-b38019ee4215">

**Comment by yanghengtang** [comment]
Pointer 4 resolved in #179

**Comment by yanghengtang** [comment]
all issues resolved
