### ISSUE TITLE
patient bugs

### ISSUE THREAD

**Issue by derekjxtan** [AY2324S1-CS2103T-T08-1/tp#172]
Tested up to edit_p based on user guide.

1. add_p error message missing newline before parameters and example.
<img width="581" alt="image" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/59358844/1a745ded-0527-4e70-a2aa-a9ddac2f2781">

2. add_p invalid phone numbers are accepted. (problem with phone validation, will move out of here)
<img width="345" alt="image" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/59358844/8df89c58-fbfb-40ad-b36b-ee13a0db9250">

3. edit_p invalid command error message parameters. What does ... mean? Nric given in example also not valid.
<img width="542" alt="image" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/59358844/16e3eacb-6360-477c-b946-5f00810c70dd">

4. edit_p success message fields order differs from user guide. User guide shows in this order: name, nric, phone
<img width="326" alt="image" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/59358844/44ce1db9-4a21-4792-a906-f8d41c8a6880">

5.

**Comment by yanghengtang** [comment]
point 3 still not resolved

**Comment by yanghengtang** [comment]
all issues resolved
