### ISSUE TITLE
[PE-D][Tester A] Grammar Errors in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-1/tp#198]
I found some grammatical errors at the top of the UG.

![image.png](https://raw.githubusercontent.com/TeeRenJing/ped/main/files/66bd7fb3-b96a-41a4-9f0c-d45bc7aeb785.png)

"... designed to aid receptionist**s** in a ..." or "... designed to aid **a** receptionist in a ..."

"... help you with your administrative task**s** in the clinic..."

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: TeeRenJing/ped#1

**Comment by derekjxtan** [comment]
fair point, to check ug for english
