### ISSUE TITLE
[PE-D][Tester D] Removed command still in the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-1/tp#207]
Perhaps it would be good to remove old commands from the UG.

![image.png](https://raw.githubusercontent.com/sopa301/ped/main/files/390318d9-942e-4e6b-81ee-085ec0fec968.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: sopa301/ped#3

**Comment by derekjxtan** [comment]
valid documentation bug, will fix
