### ISSUE TITLE
[PE-D][Tester B] Scrollbar does not appear

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-1/tp#208]
**Describe the bug**
* When resizing the width of the window, the scrollbar disappear.

**To Reproduce**
1. Resize the width to the smallest size as possible.

**Expected Behaviour**
The scrollbar should also appear until the smallest size the user can resize.

**Screenshot**

![Screenshot 2023-11-03 161918.png](https://raw.githubusercontent.com/angkyakdifp/ped/main/files/d0db0070-1511-42a5-b7b2-448d8f1c9b6d.png)

![Screenshot 2023-11-03 163434.png](https://raw.githubusercontent.com/angkyakdifp/ped/main/files/112e9a9a-7330-42ce-839a-851d2b7b6153.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: angkyakdifp/ped#3

**Comment by derekjxtan** [comment]
scroll bar disappears, but doesnt affect scrolling. See whether this is worth fixing @yanghengtang

**Comment by yanghengtang** [comment]
this is a built in feature of javafx, if all the item does not exceed the size of the list view, the scroll bar won't appear. this is the same for AB3 if there is only 1 or 2 item, the scroll bar won't be there

**Comment by yanghengtang** [comment]
not a bug
