### ISSUE TITLE
[PE-D][Tester A] Long remarks are truncated and unable to enlarge window or scroll through the remarks.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-1/tp#209]
![image.png](https://raw.githubusercontent.com/TeeRenJing/ped/main/files/99704867-ff03-4504-a6b4-defc540e654e.png)

I went to input a very long remark. This could be a patient detailing the many health conditions he has, the medication he is currently under or the past operations he has undergone.

The window cannot be enlarged, nor can I scroll to see the rest of the remark. This needs to be fixed or introduce a fixed length capacity for the length of remarks.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: TeeRenJing/ped#4

**Comment by derekjxtan** [comment]
valid issue, should fix or inform

**Comment by yanghengtang** [comment]
let's limit remarks to a certain amount of characters

**Comment by yanghengtang** [comment]
no changes to UI in v1.4, to be declared as known issue
