### ISSUE TITLE
[PE-D][Tester B] The blank space on the right panel

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-1/tp#213]
**Describe the bug**
* When maximizing the window, the right side of the main window become blank.

**To Reproduce**
1. Maximize the window size.

**Expected Behaviour**
Each of the panel in the main window should be resize to fill up the blank space

**Screenshot**

![Screenshot 2023-11-03 163732.png](https://raw.githubusercontent.com/angkyakdifp/ped/main/files/1d99dba6-7184-4867-9944-04b9a98d6d70.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: angkyakdifp/ped#4

**Comment by derekjxtan** [comment]
valid issue

**Comment by yanghengtang** [comment]
not a bug more of a user experience. unable to alter UI in v1.4
