### ISSUE TITLE
[PE-D][Tester D] Links not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-1/tp#215]
Except the Table of Contents link, the other links don't seem to work on the site. The same issues are observed in the Doctor and Patient Management Feature lists.

![image.png](https://raw.githubusercontent.com/sopa301/ped/main/files/d807ce21-e673-45a2-ac91-1f38f7d404ed.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: sopa301/ped#5

**Comment by derekjxtan** [comment]
ug issue
