### ISSUE TITLE
[PE-D][Tester C] Invalid display of Index in result display [UI][Formatting]

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-1/tp#216]
![image.png](https://raw.githubusercontent.com/sk2001git/ped/main/files/0c10ab77-6da9-46ce-bc1b-dde186656e6e.png)

![image.png](https://raw.githubusercontent.com/sk2001git/ped/main/files/8cc899d6-0f35-4535-a65a-3e2392bffa32.png)   
Result display box showing invalid index. The index is likely refering to the index internally. However remark is saved correctly 

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: sk2001git/ped#6

**Comment by derekjxtan** [comment]
error message need to show 1-based index. patients, doctors and appointment all got problem. check other commands to ensure this isnt an issue also

**Comment by cheeggered** [comment]
Same issue as #194
