### ISSUE TITLE
[PE-D][Tester A] Appointments still present even though all patients and doctors are deleted.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-1/tp#232]
![image.png](https://raw.githubusercontent.com/TeeRenJing/ped/main/files/32d8c29b-4820-4234-8acf-48b4560e6902.png)

Appointments should be deleted when the corresponding doctor/patient is deleted.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: TeeRenJing/ped#9

**Comment by derekjxtan** [comment]
Sample data issue, delete cascade works fine.
