### ISSUE TITLE
Summary of issues from pe-d

### ISSUE THREAD

**Issue by derekjxtan** [AY2324S1-CS2103T-T08-1/tp#234]
### **UG issues:**
~~#229 : `exit` command missing from command summary in ug~~ fixed
#223 : ug known issues need to specify commands (tbc)
#219 : need to mention in documentation that tags cannot have spacing, subsequent characters will be ignored
~~#215 : ug links in appointment, patient, doctor management features summary not working.~~ fixed
#212 : ug does not specify what valid parameters are.
#207 : documentation still includes removed commands
#199 : TOC should come before contents
#198 : UG english rabak

### **Management feature issues:**
~~#230 : add_a error message missing `add_a` in example~~ fixed
~~#222 : specify which nric is wrong (tbc)~~ not allowed to fix
~~#216 : remark success message shows wrong index in success message, for patients, doctors and appointments.~~ fixed

### **Infra issues:**
~~#225 : nric error message not descriptive enough, issue already raised #195~~ fixed
~~#228 : to specify that incorrect date has been entered for appointments (tbc)~~ not a bug, user reported wrong
~~#210 : parser reads extra parameters as part of the last parameter.~~ Not a problem
~~#201 : MediConnect parser doesnt check for `help` command~~ fixed

### **UI issues:**
~~#218 : view windows do not update on subsequent view commands after being minimized, affects patients, doctors and appointments.~~ fixed
~~#214 : view window does not pop up again on subsequent commands after being minimized. add on to #218. affect all also~~ fixed
~~#213 : columns do not resize.~~ technically not a bug, cannot edit appearance in v1.4
~~#209 : view window truncates remarks when it is long~~ UI problem when given extreme input declared as known issue
~~#208 : doctor column scroll bar disappears when window width is reduced~~ this indeed a feature of javafx scroll list, when the number of item does not exceed the window size, the scoller doesn't appear

### **Others:**
~~#232 : Sample data doctor nric and patient nric filpped.~~ fixed
~~#217 : link in help window still points to the AB3 user guide.~~ fixed

### **Pending:**
~~#231: unable to recreate on windows. (@kimshitong pls help to confirm this)~~ extreme input + window is designed to be non resizable
~~#226 : to constraint appointment to start and end on the same day~~ Cannot fix, argue as intended behaviour for flexibility in terms of feature

**Comment by yanghengtang** [comment]
Issues to be fixed:


Issues to be declared as known issues in UG:
#209: Remarks shown in View Window does not wrap the text into the next line
#213: Column to auto resize


Issues to be declared as planned improvement for next iteration:
#222: Specify which NRIC (doctor or patient) is invalid
#228: Specify which date-time (start or end) is invalid
