### ISSUE TITLE
Unstandardised return message for Tag feature

### ISSUE THREAD

**Issue by cheeggered** [AY2324S1-CS2103T-T08-1/tp#238]
Need to standardize the return messages for the Tag feature. Currently, the return messages can be confusing.
Have to choose whether to return the specific tag name or the person and edit the return message accordingly

<img width="1512" alt="Screenshot 2023-11-05 at 12 44 24 AM" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/122232764/f134bb3f-aa74-4434-9295-fa86adceac81">
<img width="1512" alt="Screenshot 2023-11-05 at 12 44 53 AM" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/122232764/5eb0f155-6982-4cb9-a1e9-4c825ea019be">
<img width="1512" alt="Screenshot 2023-11-05 at 12 45 37 AM" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/122232764/d6355b34-419f-423b-920e-ae979a3e7541">

**Comment by yanghengtang** [comment]
doctor specialisation is allowed to change.

appointment prescription declare as known issue
