### ISSUE TITLE
Wrong Examples in Editing a Doctor's Remark 

### ISSUE THREAD

**Issue by kimshitong** [AY2324S1-CS2103T-T08-1/tp#241]
add **specialisation** (should be add remark)

![image](https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/61624243/c781a666-3625-4cf7-b761-6fe708dddc7b)

**Comment by kimshitong** [comment]
@derekjxtan can help on verifying if this can be changed? Thanks!

**Comment by yanghengtang** [comment]
ok to change
