### ISSUE TITLE
Bug: Invalid date stores as valid date in appointment list

### ISSUE THREAD

**Issue by mounilsankar** [AY2324S1-CS2103T-T08-1/tp#268]
If an invalid date is typed in add_a command, the date wraps to nearest valid date. This is a bug with the DateTime parse method 
To reproduce:
Type in an add_a command with an invalid date such as "add_a pic\S9912343G dic\T0212385J from\2023-02-31 07:30 to\2023-02-31 08:00"
<img width="227" alt="Screenshot 2023-11-07 at 4 47 12 PM" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/98753425/558650fd-093b-48e3-8c11-3c9b509a8241">

**Comment by mounilsankar** [comment]
@yanghengtang @derekjxtan  this can be fixed right cause its outright a bug?

**Comment by derekjxtan** [comment]
Yea its a bug since we allow invalid values. But if its a issue with DateTime.parse is it even worth the effort to fix?

**Comment by mounilsankar** [comment]
Fixing it should be quite simple
