### ISSUE TITLE
DG: Appendix: Instruction for manual testing Section

### ISSUE THREAD

**Issue by mounilsankar** [AY2324S1-CS2103T-T08-1/tp#313]
Need to add testing for every testable section
<img width="752" alt="Screenshot 2023-11-13 at 12 59 23 PM" src="https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/98753425/29ed3bb9-5a86-41bc-b87b-198b543a13da">

**Comment by yanghengtang** [comment]
done
