### ISSUE TITLE
Navigation for Parameters

### ISSUE THREAD

**Issue by kimshitong** [AY2324S1-CS2103T-T08-1/tp#335]
Shall we put a **Back to [Table of Contents](https://ay2324s1-cs2103t-t08-1.github.io/tp/UserGuide.html#table-of-contents).** under this parameter table

![image](https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/61624243/fdc358a8-fe23-448f-8c35-51993771567a)

**Comment by yanghengtang** [comment]
just add
