### ISSUE TITLE
UG : Adding a Patient

### ISSUE THREAD

**Issue by kimshitong** [AY2324S1-CS2103T-T08-1/tp#336]
1. Do you want consider put this "Back to Patient Management Features" to below after the tips instead.
2. **numbers**

@cheeggered 
![image](https://github.com/AY2324S1-CS2103T-T08-1/tp/assets/61624243/e8d3ff47-3f8b-42ca-a7a1-7a9a7a2e942d)

**Comment by yanghengtang** [comment]
just swap
